import React from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Lightbulb, ArrowRight, Sparkles, CheckCircle2 } from 'lucide-react';

export const ActionRecommendations: React.FC = () => {
  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4 pb-2 border-b border-[#1E3452]/60">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl sm:text-2xl font-bold text-white tracking-tight flex items-center gap-2">
              <Lightbulb className="w-6 h-6 text-[#E94E97]" />
              AI Next Best Action Recommendations
            </h1>
            <Badge variant="magenta" size="sm">
              Continuous Agent Guidance
            </Badge>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Prioritized prescriptive recommendations generated by Aura AI for Account Executives and Revenue Leaders.
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {[
          {
            title: 'Schedule Executive Alignment Call for Datadog Account',
            reasoning: 'Intent score reached 92/100 following repeated downloads of security whitepaper by VP Infrastructure.',
            recommendedActor: 'Enterprise AE Sarah Jenkins',
            impact: '+$240,000 ARR Opportunity',
            priority: 'High Priority',
          },
          {
            title: 'Offer Multi-Year Contract Commitment Incentive to Vercel',
            reasoning: 'Competitive counter-offer detected from rival vendor. Applying 12% discount boosts win probability from 64% to 88%.',
            recommendedActor: 'Deal Desk & Legal Team',
            impact: '+$120,000 ARR Protected',
            priority: 'Medium Priority',
          },
        ].map((item, idx) => (
          <Card key={idx} hoverEffect>
            <CardContent className="p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="space-y-1.5 flex-1">
                <div className="flex items-center gap-2">
                  <Badge variant={idx === 0 ? 'orange' : 'purple'} size="sm">
                    {item.priority}
                  </Badge>
                  <span className="text-xs font-mono text-emerald-400">{item.impact}</span>
                </div>
                <h3 className="text-sm font-semibold text-white">{item.title}</h3>
                <p className="text-xs text-slate-400">{item.reasoning}</p>
                <div className="text-[11px] font-mono text-slate-500 pt-1">
                  Assignee: <span className="text-[#16C5D8]">{item.recommendedActor}</span>
                </div>
              </div>

              <Button variant="primary" size="sm" rightIcon={<ArrowRight className="w-3.5 h-3.5" />}>
                Execute Action
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
};
