import React, { useState } from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { ConfidenceMeter } from '../components/ui/ConfidenceMeter';
import { useAppStore } from '../store/useAppStore';
import { Lightbulb, ArrowRight, Sparkles, CheckCircle2, Zap, ShieldCheck, UserCheck, DollarSign } from 'lucide-react';
import { formatCurrency } from '../lib/utils';

export const ActionRecommendations: React.FC = () => {
  const { setActiveModule, approveAction } = useAppStore();
  const [filterRole, setFilterRole] = useState<'all' | 'ae' | 'revops'>('all');

  const recommendations = [
    {
      id: 'rec-1',
      title: 'Dispatch C-Level Email Sequence for Stripe EMEA Expansion',
      company: 'Stripe Technologies Inc.',
      reasoning: 'Intent score reached 98/100 following 3 VP Sales hires in EMEA and expansion announcement.',
      recommendedActor: 'VP RevOps Alex Mercer',
      roleCategory: 'revops',
      impact: 185000,
      confidence: 98.2,
      priority: 'High Priority',
      actionType: 'Outreach Dispatch',
    },
    {
      id: 'rec-2',
      title: 'Schedule Executive Alignment Call for Datadog Account',
      company: 'Datadog Systems',
      reasoning: 'Spike in G2 Crowd Cloud Security intent and 4 security whitepaper downloads.',
      recommendedActor: 'Enterprise AE Sarah Jenkins',
      roleCategory: 'ae',
      impact: 240000,
      confidence: 94.5,
      priority: 'High Priority',
      actionType: 'Account Re-routing',
    },
    {
      id: 'rec-3',
      title: 'Offer Multi-Year Contract Commitment Incentive to Vercel',
      company: 'Vercel Platform Cloud',
      reasoning: 'Competitive counter-offer detected from rival vendor. 12% multi-year discount boosts win rate to 88%.',
      recommendedActor: 'Deal Desk & AE Lead',
      roleCategory: 'ae',
      impact: 120000,
      confidence: 89.1,
      priority: 'Medium Priority',
      actionType: 'Discount Override',
    },
  ];

  const filtered = recommendations.filter((r) => {
    if (filterRole === 'ae') return r.roleCategory === 'ae';
    if (filterRole === 'revops') return r.roleCategory === 'revops';
    return true;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-2 border-b border-[#1E3452]/60">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl sm:text-2xl font-bold text-white tracking-tight flex items-center gap-2">
              <Lightbulb className="w-6 h-6 text-[#E94E97]" />
              AI Next Best Action Recommendations
            </h1>
            <Badge variant="magenta" size="sm">
              Prescriptive Intelligence
            </Badge>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Prioritized prescriptive recommendations generated by Aura AI for Account Executives and Revenue Leaders.
          </p>
        </div>

        <div className="flex items-center bg-[#040B14] p-1 rounded-lg border border-[#1E3452] text-xs font-mono">
          {(['all', 'ae', 'revops'] as const).map((role) => (
            <button
              key={role}
              onClick={() => setFilterRole(role)}
              className={`px-3 py-1 rounded capitalize transition-all cursor-pointer ${
                filterRole === role
                  ? 'bg-[#081426] text-[#16C5D8] font-bold border border-[#16C5D8]/30'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              {role === 'all' ? 'All Roles' : role === 'ae' ? 'AE Reps' : 'RevOps Leadership'}
            </button>
          ))}
        </div>
      </div>

      {/* Recommendations List */}
      <div className="space-y-4">
        {filtered.map((item) => (
          <Card key={item.id} hoverEffect>
            <CardContent className="p-5 flex flex-col md:flex-row md:items-center justify-between gap-6">
              <div className="space-y-2 flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge variant={item.priority === 'High Priority' ? 'orange' : 'purple'} size="sm">
                    {item.priority}
                  </Badge>
                  <Badge variant="cyan" size="sm">
                    {item.actionType}
                  </Badge>
                  <span className="text-xs font-mono text-emerald-400 font-bold">
                    +{formatCurrency(item.impact)} Potential ARR
                  </span>
                </div>

                <h3 className="text-sm font-semibold text-white">{item.title}</h3>

                <p className="text-xs text-slate-300 font-mono bg-[#040B14] p-3 rounded-lg border border-[#1E3452]/80">
                  "{item.reasoning}"
                </p>

                <div className="flex items-center justify-between text-[11px] font-mono text-slate-400 pt-1">
                  <span>
                    Target Assignee: <span className="text-[#16C5D8] font-semibold">{item.recommendedActor}</span>
                  </span>
                  <span className="text-slate-500">{item.company}</span>
                </div>
              </div>

              {/* Right Side Confidence & Action */}
              <div className="flex flex-col items-end justify-between gap-3 shrink-0 min-w-[200px] border-t md:border-t-0 md:border-l border-[#1E3452]/60 pt-3 md:pt-0 md:pl-6">
                <ConfidenceMeter score={item.confidence} label="Recommendation Fit" size="sm" />

                <Button
                  variant="primary"
                  size="sm"
                  glow
                  className="w-full"
                  leftIcon={<Zap className="w-3.5 h-3.5 text-[#040B14]" />}
                  onClick={() => setActiveModule('approvals')}
                >
                  Execute Action
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
};
